export const mockCars = [
  {
    id: 1,
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    pricePerDay: '250.00',
    imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=2115&auto=format&fit=crop',
    type: 'Sports',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 4,
    available: true,
  },
  {
    id: 2,
    brand: 'Mercedes',
    model: 'G-Class AMG',
    year: 2023,
    pricePerDay: '350.00',
    imageUrl: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?q=80&w=1974&auto=format&fit=crop',
    type: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 5,
    available: true,
  },
  {
    id: 3,
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    pricePerDay: '200.00',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=2071&auto=format&fit=crop',
    type: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Electric',
    seats: 5,
    available: true,
  },
  {
    id: 4,
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2023,
    pricePerDay: '300.00',
    imageUrl: 'https://images.unsplash.com/photo-1503376762279-5ebf98144cd9?q=80&w=2070&auto=format&fit=crop',
    type: 'Sports',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    seats: 2,
    available: true,
  },
  {
    id: 5,
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2024,
    pricePerDay: '220.00',
    imageUrl: 'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?q=80&w=1974&auto=format&fit=crop',
    type: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Electric',
    seats: 5,
    available: true,
  },
  {
    id: 6,
    brand: 'Toyota',
    model: 'Land Cruiser 300',
    year: 2024,
    pricePerDay: '150.00',
    imageUrl: 'https://images.unsplash.com/photo-1594502184342-2e12f877aa73?q=80&w=2070&auto=format&fit=crop',
    type: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    seats: 7,
    available: true,
  }
];

export const mockBrands = [
  { name: 'Audi', logo: '/images/audi.png' },
  { name: 'BMW', logo: '/images/bmw.png' },
  { name: 'Mercedes', logo: '/images/mercedes.png' },
  { name: 'Tesla', logo: '/images/tesla.png' },
  { name: 'Toyota', logo: '/images/toyota.png' },
  { name: 'Porsche', logo: '/images/porsche.png' }
];
